### ISSUE TITLE
LESS support

### ISSUE THREAD

**Issue by jaulz** [gocardless/es6-angularjs#3]
Is there any possibility to add LESS support? Do I need to change the css.js file?

**Comment by maxmurdoch** [comment]
@jaulz I think you’re right. The `script/css` file executes the code in `css.js`, which is then called in the build step alongside `script/precompile` in both `script/start` and `script/build`. Therefore you would need change `css.js` to put your source `*.css` files through `less` instead of `rework`. I am only 90% sure of this so @jackfranklin please could you confirm or deny?

**Comment by jackfranklin** [comment]
Yup - it all runs through `lib/css.js` so you should alter the code there.
